name: flutter_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  elementary: ^3.2.1
  elementary_helper: ^1.0.3
  auto_route: ^10.1.0+1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  auto_route_generator: ^10.1.0
  flutter_lints: ^2.0.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets: 
    - assets/
